# Generated by Django 4.1.7 on 2023-04-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_location', models.CharField(max_length=50)),
                ('hotel_star', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='roominformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
