# Generated by Django 4.1.7 on 2023-04-10 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('payment', models.IntegerField()),
                ('roominformation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.roominformation')),
            ],
        ),
    ]
