# Generated by Django 4.1.7 on 2023-04-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoteltransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation')),
            ],
        ),
    ]
